### ISSUE TITLE
Error: Cannot find module './lib/mdbconverter'

### ISSUE THREAD

**Issue by thecalle** [Advantech-IIoT/node-red-contrib-mdbconverter#2]
Manual install on Raspberry PI using shell in ./node-red directory.
Node present in list, but get error running it in flow.

**Comment by thecalle** [comment]
I think is due to mdbconverter.node compiled for 32bit or 64, but not for ARM

**Comment by ChicLee0819** [comment]
Sorry, we do not support arm or Linux
