### ISSUE TITLE
wrong Module version

### ISSUE THREAD

**Issue by Dunkhase** [Advantech-IIoT/node-red-contrib-mdbconverter#3]
Hi all, i need your help. I have the following Problem with node-red and mdbconverter.
Sorry but i can't find the problem.
Error: The module '\\?\C:\Users\DEBR.....\.node-red\node_modules\node-red-contrib-mdbconverter\lib\mdbconverter.node'was compiled against a different Node.js version usingNODE_MODULE_VERSION 48. This version of Node.js requiresNODE_MODULE_VERSION 67. Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`).

My problem is i can't run this under node.js Version6.x, or i have problems with other nodes.
For example modbus server. Is there a simple way to recompile with the actual version of node.js?

Regards
Holger

**Comment by h2oil** [comment]
@Dunkhase  did you get this working?

**Comment by thkfighter** [comment]
I run into the same problem.  -_-||

**Comment by ChicLee0819** [comment]
We updated for NODE_MODULE_VERSION=64
