### ISSUE TITLE
Error code 255

### ISSUE THREAD

**Issue by thkfighter** [Advantech-IIoT/node-red-contrib-mdbconverter#4]
All three nodes throw an error code 255. The help of Modbus Data Converter says the error code 255 means invalid device. Is node-red-contrib-mdbvonverter limited to Advantech devices?

**Comment by ChicLee0819** [comment]
Please install Platform-SDK to v0.03.018

[Platform-SDK V0.03.018](https://github.com/Advantech-IIoT/Platform-SDK/tree/master/windows/bin/V0.03.018)
